DECLARE vdt_id DATE DEFAULT @vdt_id;

delete from `data-bi-prd-935c.bi_mart.angie_hrchy_dim_hst` where mth = date_trunc(vdt_id,month);

insert into `data-bi-prd-935c.bi_mart.angie_hrchy_dim_hst`
select date_trunc(vdt_id,month) mth, 
cast(angie_hrchy_sk_id as string) angie_hrchy_sk_id,
cast(mp3_channel_sk_id as string) mp3_channel_sk_id,
row_id,
par_partner_id,
partner_id,
geo_row_id,
partner_qr_cd,
partner_type,
partner_status,
retailer_name,
canvasser_id,
canvasser_name,
canvasser_location,
sub_mp3_id,
sub_mp3_name,
sub_mp3_location,
tm_id,
tm_name,
tm_location,
ts_id,
ts_name,
ts_location,
mp3_id,
mp3_name,
mp3_location,
bm_id,
bm_name,
bm_location,
rsh_id,
rsh_name,
rsh_location,
roh_id,
roh_name,
roh_location,
hoo_id,
hoo_name,
hoo_location,
csh_name,
csh_id,
csh_location,
partner_dob,
partner_bank_acct,
partner_bank_nm,
partner_addr,
partner_city,
partner_country,
partner_email_add,
partner_mobile,
partner_shop_nm,
source_system_nm,
created_dtm,
updated_dtm,
cast(load_id as string),
ret_hierarchy_type,
company_address,
company_city,
company_name,
company_zipcode,
company_zone,
test_flag,
ret_active_date,
creditcard_number,
hrchy_type,
partner_code,
additional_recepient,
cast(serv_player_start_dt as string) serv_player_start_dt,
cast(serv_player_last_dt as string) serv_player_last_dt,
whitelisted_flag,
sppkp_date,
sppkp_id,
sppkp_id_modi_date,
ktp_id_modi_date,
npwp,
npwp_date,
npwp_id_modi_date,
npwp_name,
npwp_type,
ktp_id,
ret_segment,
sp_id,
sp_name,
sp_location,
ret_region
from `data-dtptechm-prd-c7ca.dwh.angie_hrchy_dim`;